### ISSUE TITLE
Limited by 100KB limitation to expand our app

### ISSUE THREAD

**Issue by customerhub** [Shopify/theme-extension-getting-started#22]
Hi Shopify TAE team,

I wanted to enquire here and see if there is any plans or ways to go past the very limited 100kb liquid limit set on Theme App Extensions.

This limitation is applied across all liquid within an app, and we have multiple extensions that add functionality within our merchants shops - and have plans for others as well as to expand our existing functionality.

We have optimised about as much as we can, and now we are at the point of constantly hitting that 100kb limit when we try to add something else to our app. 

This limit is debilitating to our progress. We attended Unite, and were told to post here. If you would like more details on our use case, please PM me and I can provide any details you wish. 

We hope you can lift the limit to ~300-500kb - which would provide us enough run-way to expand on our app while keeping optimisation in mind.

I have posted in the Slack channels as well - but no love there. We hope someone @shopify-admins can reply and provide us some insight and resolution of this issue so we can continue to provide more to merchants.

**Comment by adithwip** [comment]
Hey, have this issue been resolved?
I have the same issue with the 10000 bytes threshold.
Eventually, I was told to visit this Repo as well after asking countless Shopify support channels.

**Comment by flourishpool** [comment]
Our team also copes with the 100kb liquid file and 25-setting-per-block limit limitations when working with Theme App Extensions on our Shopify app. 

We tried to reach out to the Shopify support team (both via the ticket and live chat), but the situation is still under consideration. 

For our case, we need to support a rich set of configurations for the app blocks to cover different use cases that the merchants might need. However, we quickly reach the 25-setting-per-app-block and 100kb liquid file limit. 

For example, in the blocks like Tabs, Accordion.. (in our app), we can only define a maximum of 6 items (each item has about 3-4 settings of title, icon and description). Merchants will find our pre-built settings too limited and need extra configurations for their specific customization of spacing, thumbnail, text size, animation, etc. (which are unavailable due to the 25-setting-per-block limit).

I really hope the Shopify development team will consider lifting the hard limits (100kb liquid file and 25-settings-per-block) to truly explore the 'section everywhere' on the Online Store 2.0. 

Under this circumstance, we have to think of adding a separate app to extend the features, which is really bad in terms of UX and app performance (More apps to achieve one single goal - Shopify store design).

I believe if the TAE limit as mentioned above is resolved, we can expect more agencies leveraging add-on components to augment free or paid themes—such as Shopify’s own Dawn theme—rather than developing everything from scratch as you referred to in this article: https://www.shopify.com/partners/blog/development-trends-2023

**Comment by cbothner** [comment]
The new version of the CLI shipped today, which updates the client-side validation with the increased limit. Thank you all for this feedback.
